apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: demo-pipeline
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: demo-pipeline
  params:
    - name: repo-url
      value: git@github.com:saloyiana/tekton.git
    - name: branch-name
      value: master
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Mi
