apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: runner
spec:
  serviceAccountName: build-bot
  taskRef:
    name: build-docker-image-from-git-source
  params:
  - name: IMAGE
    value: "saloyiana/alpine:1"
  resources:
    inputs:
    - name: docker-source
      resourceRef:
        name: skaffold-git
