apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: to-lower
spec:
  description: |
    This task read and process a file from the workspace and write the result
    both to a file in the workspace and as a Task Result
  params:
    - name: input-path
      type: string
  results:
    - name: message
      description: Input message in lower case
  steps:
    - name: to-lower
      image: ubuntu
      script: cat $(workspaces.w.path)/$(params.input-path) | tr '[:upper:]' '[:lower:]' | tee $(workspaces.w.path)/lower $(results.message.path)
  workspaces:
    - name: w
