apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: result-reporter
spec:
  description: |
    This task is supposed to mimic a service that post data from the Pipeline,
    e.g. to an remote HTTP service or a Slack notification.
  params:
    - name: result-to-report
      type: string
  steps:
    - name: report-result
      image: ubuntu
      script: echo $(params.result-to-report)
